### ISSUE TITLE
Register ApplicationBuilderAppUtils in General Registry

### ISSUE THREAD

**Issue by NHDaly** [NHDaly/ApplicationBuilderAppUtils.jl#1]
@JuliaRegistrator register()

**Comment by NHDaly** [comment]
@JuliaRegistrator register()

**Comment by NHDaly** [comment]
@JuliaRegistrator register()

**Comment by NHDaly** [comment]
@JuliaRegistrator register()

**Comment by NHDaly** [comment]
@JuliaRegistrator register()

**Comment by fredrikekre** [comment]
Do you know whats wrong @nkottary?

**Comment by nkottary** [comment]
`Pkg.Types.read_project` says ``Info: Unexpected error: MethodError: Cannot `convert` an object of type Int64 to an object of type String``. I think its because Project.toml does not quote the julia version.

**Comment by NHDaly** [comment]
@JuliaRegistrator register()

**Comment by NHDaly** [comment]
Ooops, thank @nkottary!
